/**
 * Localization configuration file for Bet On Me Terminal.
 * 
 * Includes professional bilingual dictionary assets for the Landing page (IntroPage),
 * the dedicated Authentication Portal (AuthPage), and the entire dashboard application (APP_LOCALIZATION).
 * 
 * - English is purely English (no Burmese mixing).
 * - Burmese uses a hybrid translation, incorporating familiar English technical/financial terms 
 *   to sound natural and professional to local users.
 */

export const AUTH_LOCALIZATION = {
  en: {
    title: "Access Secure Personal Terminal",
    subtitle: "Synchronize your consistency candlesticks, habit assets, and personal discipline multipliers across the secure cloud database.",
    emailLabel: "Terminal Email Identity",
    passwordLabel: "Cryptographic Password",
    confirmPasswordLabel: "Confirm Password Validation",
    googleBtn: "Authenticate with Google",
    orDivider: "OR ENTER VIA EMAIL KEY",
    submitBtnSignIn: "Decrypt & Enter Terminal",
    submitBtnSignUp: "Deploy New Cloud Portfolio",
    switchTextSignIn: "New operator?",
    switchBtnSignIn: "Deploy New Account",
    switchTextSignUp: "Already registered?",
    switchBtnSignUp: "Access Existing Account",
    guestBtn: "Bypass to local Offline Mode",
    guestWarning: "Important: Your discipline performance data will only be stored in local browser cache. It will NOT sync to the cloud database.",
    loadingText: "Synchronizing with database network...",
    emailRequired: "Please enter a valid email address.",
    passwordTooShort: "Password must be at least 6 characters.",
    passwordMismatch: "Confirmation password does not match.",
    googleError: "Google authentication failed. Please retry or enter email.",
    successSignUp: "Cloud portfolio deployed successfully! Booting main engine...",
    successSignIn: "Authorization token validated! Decrypting terminal...",
    securityWarning: "SECURITY WARNING",
    accessGranted: "ACCESS GRANTED",
    backToLanding: "← Back to Intro Page",
    by: "Bet On Me Core Security Framework"
  },
  my: {
    title: "Terminal သို့ ဝင်ရောက်ရန်",
    subtitle: "သင်၏ Candlestick ဇယားများ၊ Habit Assets များနှင့် ကိုယ်ပိုင် Discipline ရမှတ်များကို စနစ်တကျ ထိန်းသိမ်းရန် Cloud Database တွင် သိမ်းဆည်းပါ။",
    emailLabel: "အီးမေးလ်လိပ်စာ (Email Address)",
    passwordLabel: "လျှို့ဝှက်နံပါတ် (Password)",
    confirmPasswordLabel: "လျှို့ဝှက်နံပါတ် ပြန်ရိုက်ရန်",
    googleBtn: "Google Account ဖြင့် တိုက်ရိုက်ဝင်မည်",
    orDivider: "သို့မဟုတ် Email ဖြင့် ဝင်ရောက်ရန်",
    submitBtnSignIn: "Terminal ထဲသို့ ဝင်ရောက်မည်",
    submitBtnSignUp: "အကောင့်အသစ် ဖွင့်လှစ်မည်",
    switchTextSignIn: "အကောင့်မရှိသေးဘူးလား?",
    switchBtnSignIn: "အကောင့်အသစ် ဖွင့်ရန်",
    switchTextSignUp: "အကောင့် ရှိပြီးသားလား?",
    switchBtnSignUp: "အကောင့်ဟောင်းဖြင့် ဝင်ရန်",
    guestBtn: "ဧည့်သည်စနစ် (Offline Mode) ဖြင့် စမ်းသပ်မည်",
    guestWarning: "အသိပေးချက် - Offline Mode တွင် သင့်မှတ်တမ်းများကို browser cache တွင်သာ ယာယီသိမ်းဆည်းမည်ဖြစ်ပြီး Cloud ပေါ်သို့ back up လုပ်ပေးနိုင်မည် မဟုတ်ပါ။",
    loadingText: "Database Server သို့ ချိတ်ဆက်နေပါသည်...",
    emailRequired: "မှန်ကန်သော Email Address ရိုက်ထည့်ပေးပါ။",
    passwordTooShort: "Password သည် အနည်းဆုံး စာလုံး ၆ လုံး ရှိရပါမည်။",
    passwordMismatch: "Password ပြန်ရိုက်သည်မှာ ကိုက်ညီမှုမရှိပါ။",
    googleError: "Google account ချိတ်ဆက်မှု အဆင်မပြေပါ။ Email ဖြင့် ပြန်လည်ကြိုးစားပေးပါ။",
    successSignUp: "အကောင့်အသစ် ဖွင့်လှစ်ခြင်း အောင်မြင်ပါသည်! Terminal သို့ ဝင်ရောက်နေသည်...",
    successSignIn: "စစ်ဆေးမှု အောင်မြင်ပါသည်! Terminal သို့ ဝင်ရောက်နေသည်...",
    securityWarning: "လုံခြုံရေး သတိပေးချက်",
    accessGranted: "ခွင့်ပြုချက် ရရှိပါပြီ",
    backToLanding: "← ရှေ့စာမျက်နှာသို့ ပြန်သွားရန်",
    by: "Bet On Me Security Control"
  }
};

export const INTRO_LOCALIZATION = {
  en: {
    heroTag: "🚀 REIMAGINING PERSONAL ACCOUNTABILITY",
    heroTitle: "BET ON YOURSELF WITH",
    heroTitleHighlight: "ABSOLUTE DISCIPLINE",
    heroDesc: "Bet On Me is the first Gamified Habit Terminal that transforms your daily consistency into tradeable equity index. Watch your habits chart like real stock tickers, predict your growth margins, apply custom leverage, and unlock premium PUBG-style ranks.",
    startBtn: "Start Habit Trading Now",
    seeHowBtn: "See Core Mechanics",
    closeTour: "Close System Tour",
    
    pillar1Title: "100% Habit Candlestick Charts",
    pillar1Desc: "Your daily execution forms real financial candlesticks (Open, High, Low, Close). Checking off habits creates a massive Bullish green surge; missing them triggers a Bearish red gap.",
    
    pillar2Title: "Interactive Predictor Terminal",
    pillar2Desc: "Wager points on your 1, 3, or 7-day habit streaks. Amplify rewards by selecting up to 15x leverage multipliers, but manage risk to prevent portfolio liquidation.",
    
    pillar3Title: "Rank Promotion Challenges",
    pillar3Desc: "Uniquely designed PUBG-style ranks (Bronze to Conqueror). Leveling up unlocks high leverage and limits, but demands intense accountability with higher penalty rates.",
    
    featuresTitle: "System Operations & Protocols",
    featuresSub: "A detailed breakdown of the custom algorithms governing your terminal account.",
    
    tabChart: "1. Candlestick Index Price",
    tabChartDesc: "Asset weights, Doji & Bullish candle calculations",
    tabPredict: "2. Predictor & Leverage",
    tabPredictDesc: "Staking contracts, target thresholds, & margin calls",
    tabRanks: "3. PUBG-Style Rank Levels",
    tabRanksDesc: "Unlockable leverage, wager limits, & penalty rates",
    tabRules: "4. Localized Schedule Graces",
    tabRulesDesc: "Night Owl offsets, Weekend mode, & Custom Days",
    
    // Feature detailed panels
    feat1Title: "Real-Time Habit Index Asset Engine",
    feat1Desc: "Every habit you declare acts as a high-fidelity 'Habit Asset' in your index. They carry custom risk levels (Low, Medium, High) affecting daily index volatility. Checking off a 'Best To Do' asset results in a massive price spike, while neglecting key responsibilities triggers an immediate margin collapse.",
    feat1Sub1: "All Habits Completed (100% Consistency)",
    feat1Sub1Desc: "🟢 Bullish Candle: Intense close price surge + dynamic daily points bonus credited.",
    feat1Sub2: "Partial Habits Completed (40% - 80% Consistency)",
    feat1Sub2Desc: "🟡 Doji / Sideways Candle: Minimal price fluctuations, standard market balance.",
    feat1Sub3: "Zero Habits Completed (0% Consistency)",
    feat1Sub3Desc: "🔴 Bearish Candle: Heavy intraday market dump + automatic Miss Penalty deduction.",
    feat1Tip: "You can toggle technical overlay indicators like SMA (Simple Moving Average) and EMA (Exponential Moving Average) directly in your Settings tab.",
    
    feat2Title: "Interactive Predictor Terminal with Custom Leverage",
    feat2Desc: "Do you trust your consistency? Put real skin in the game! Stake points on your own execution over selected timeframes. Apply high leverage multipliers to scale up rewards, but be careful—falling below target triggers immediate margin liquidation.",
    feat2Low: "LOW RISK",
    feat2LowTitle: "1-Day Quick Scalp",
    feat2LowDesc: "1% Growth Target / +15% Base Bonus / Low leverage cap",
    feat2Med: "MED RISK",
    feat2MedTitle: "3-Day Swing Trade",
    feat2MedDesc: "4% Growth Target / +45% Base Bonus / Perfect risk-reward balance",
    feat2High: "HIGH RISK",
    feat2HighTitle: "7-Day Ultimate Run",
    feat2HighDesc: "10% Growth Target / +150% Base Bonus / Ultimate commitment",
    feat2Tip: "Liquidation events automatically write off wagered points and log transactions inside your Account Ledger.",
    
    feat3Title: "PUBG-Style Rank Tiers & Miss Penalties",
    feat3Desc: "Your points represent your ultimate trading capital. Accumulating points moves you up the ranks. High ranks grant elite terminal rights, including increased max bet limits and leverage multipliers. However, high-tier traders face strict scrutiny: the penalty percentage multiplier for missed habits scales significantly.",
    feat3ColRank: "Rank & Status",
    feat3ColLimits: "Max Bet / Leverage",
    feat3ColPenalty: "Penalty Multiplier",
    feat3ColRange: "Points Bracket",
    feat3Bronze: "🥉 Bronze",
    feat3Silver: "🥈 Silver",
    feat3Gold: "🥇 Gold",
    feat3Plat: "💎 Platinum",
    feat3Diamond: "💠 Diamond",
    feat3Crown: "👑 Crown",
    feat3Conq: "🌟 Conqueror",
    feat3Tip: "Reaching the end of a tier locks your points and triggers a 3-Day Promotion Match. You must maintain 75% consistency for 3 days to confirm rank promotion.",
    
    feat4Title: "Localized Schedule Controls for Real Lifestyles",
    feat4Desc: "Your terminal adapts to your life, not the other way around. Configure advanced scheduling controls to protect your streak score during intense weeks.",
    feat4OwlTitle: "Night Owl Grace Hour Offset",
    feat4OwlDesc: "Shift your daily day boundary from 12:00 AM up to 4:00 AM. Keep logging habits past midnight without breaking your daily streak.",
    feat4WeekendTitle: "Weekend Protection Mode",
    feat4WeekendDesc: "Exclude Saturday and Sunday from missed-habit penalty audits. Ideal for maintaining a healthy rest-work balance.",
    feat4SelectiveTitle: "Selective Custom Days",
    feat4SelectiveDesc: "Configure habits to trigger only on specific days (e.g., gym on Mon/Wed/Fri). Days off are automatically treated as rest periods without penalizing your score.",
    
    progTitle: "Progression Ladder & Rewards",
    progSub: "Compare your current standing with the elite ranks. Can you reach the Conqueror tier?",
    yourRank: "Your Active Rank",
    
    guideTitle: "Four Steps to Master the Terminal",
    guideSub: "Quick start roadmap to build financial-style discipline.",
    step1Title: "1. Asset Deployment",
    step1Desc: "Go to the Assets Tab and declare your habits. Configure risk levels, custom days, and points weightings.",
    step2Title: "2. Daily Execution",
    step2Desc: "Carry out your routine. Mark habits on the live checklist in the Overview tab before your day boundary closes.",
    step3Title: "3. Chart Auditing",
    step3Desc: "Analyze your performance on the Candlestick Chart. Monitor market trends, moving averages, and index volatility.",
    step4Title: "4. Leveraged Betting",
    step4Desc: "Wager points in the Predictor Terminal. Boost consistency through real skin-in-the-game stakes.",
    
    footerTxt: "Bet On Me Terminal • Professional Consistency System v1.5.0 • Crafted for high-performance builders.",
    readyTitle: "System Online & Authorized",
    readyDesc: "Take control of your execution. Put skin in the game, trade your habits, and maximize your performance portfolio today."
  },
  my: {
    heroTag: "🚀 စည်းကမ်းကို နည်းပညာအသွင်ပြောင်းလဲခြင်း",
    heroTitle: "ကိုယ့်ကိုယ်ကိုယ် ပြန်လည်",
    heroTitleHighlight: "လောင်းကြေးထပ်ပါ",
    heroDesc: "Bet On Me သည် သင့်လုပ်ဆောင်ရမည့် နေ့စဉ်အလေ့အကျင့်များကို အဖိုးတန် Asset ရှယ်ယာများအဖြစ် ပြောင်းလဲပေးသည့် ပထမဆုံး Gamified Habit Terminal ဖြစ်သည်။ စတော့ရှယ်ယာဈေးကွက်ပုံစံ Candlestick ဇယားများဖြင့် performance အတက်အကျကို စောင့်ကြည့်ပြီး၊ ရရှိလာသည့် points များကို Leverage တင်ကာ ခန့်မှန်းချက်များဖြင့် တိုးပွားအောင် ကစားနိုင်မည်ဖြစ်သည်။",
    startBtn: "စတင်အသုံးပြုမည်",
    seeHowBtn: "လုပ်ဆောင်ပုံအသေးစိတ်",
    closeTour: "လမ်းညွှန်ပိတ်မည်",
    
    pillar1Title: "100% Habit Candlestick Charts",
    pillar1Desc: "နေ့စဉ် checklist ပြီးမြောက်မှုများကို စတော့ရှယ်ယာများကဲ့သို့ Open, High, Low, Close ဇယားများဖြင့် ပြသပေးသည်။ ပြီးမြောက်ပါက အစိမ်းရောင် Bullish Candle တက်မည်ဖြစ်ပြီး ပျက်ကွက်ပါက အနီရောင် Bearish ဖြစ်သွားပါမည်။",
    
    pillar2Title: "Interactive Predictor Terminal",
    pillar2Desc: "သင့်ရဲ့ အနာဂတ်စည်းကမ်းအပေါ် Points များဖြင့် လောင်းကြေးထပ်ပါ။ Leverage ကို ၁၅ ဆအထိ တိုးမြှင့်တင်ပြီး Predictor Terminal တွင် Bonus Points ဆုများကို ဆတိုး တိုးမြင့်ရယူနိုင်ပါသည်။",
    
    pillar3Title: "Rank Promotion Challenges",
    pillar3Desc: "ရမှတ်စုဆောင်းပြီး Bronze မှ Conqueror အဆင့်အထိ တက်လှမ်းပါ။ Rank မြင့်လာပါက Max Bet ပမာဏနှင့် Leverage Multipliers များ ပိုမိုရရှိမည်ဖြစ်သော်လည်း Miss Penalty ဒဏ်ကြေး ပိုများလာပါမည်။",
    
    featuresTitle: "System Operations & Protocols",
    featuresSub: "Habit Terminal ၏ လုပ်ဆောင်ပုံစနစ်တစ်ခုချင်းစီကို အသေးစိတ် ဖော်ပြပေးထားပါသည်။",
    
    tabChart: "၁။ Candlestick Index Price",
    tabChartDesc: "Asset ဈေးနှုန်းနှင့် Doji & Bullish Candle တွက်ချက်ပုံ",
    tabPredict: "၂။ Predictor & Leverage",
    tabPredictDesc: "Points စုဆောင်းမှုနှင့် Risk Level စီမံခန့်ခွဲမှု",
    tabRanks: "၃။ PUBG-Style Rank Tiers",
    tabRanksDesc: "Bronze မှ Conqueror အဆင့်သတ်မှတ်ချက်များ",
    tabRules: "၄။ Night Owl & Custom Days",
    tabRulesDesc: "အိပ်ချိန်နောက်ကျသူများနှင့် သီးသန့်ရက်ရွေးချယ်မှု",
    
    // Feature detailed panels
    feat1Title: "Real-Time Habit Index Asset Engine",
    feat1Desc: "သင့်ရဲ့ အလေ့အကျင့်တစ်ခုစီဟာ ရိုးရိုးသက်သက် checklist မဟုတ်တော့ပါဘူး။ ၎င်းတို့ဟာ နေ့စဥ် ဈေးနှုန်းတက်လှမ်းစေမည့် အဖိုးတန် Asset များဖြစ်ကြသည်။ အလေ့အကျင့်တစ်ခုချင်းစီ၏ Risk Level (Low, Medium, High) ပေါ်မူတည်၍ Intraday Volatility (ဈေးနှုန်းအတက်အကျ) အား သက်ရောက်စေမည်ဖြစ်သည်။ အရေးကြီးသော 'Best To Do' အလေ့အကျင့် ပျက်ကွက်ပါက Margin Crash ကဲ့သို့ ဈေးနှုန်းထိုးကျသွားစေမည်။",
    feat1Sub1: "အလေ့အကျင့်အားလုံး ပြီးမြောက်ပါက (100% Consistency)",
    feat1Sub1Desc: "🟢 Bullish Candle: ဈေးနှုန်းအဆမတန်မြင့်တက်ပြီး Bonus Points များ ရရှိပါမည်။",
    feat1Sub2: "၄၀% မှ ၈၀% အထိ ပြီးမြောက်ပါက",
    feat1Sub2Desc: "🟡 Doji / Sideways Candle: ဈေးနှုန်းငြိမ်နေပြီး အပြောင်းအလဲနည်းပါးမည်။",
    feat1Sub3: "လုံးဝ ပျက်ကွက်ပါက (0% Consistency)",
    feat1Sub3Desc: "🔴 Bearish Candle: ဈေးနှုန်းထိုးကျပြီး Miss Penalty ဒဏ်ကြေး နုတ်ယူခြင်းခံရမည်။",
    feat1Tip: "Settings tab ထဲတွင် SMA (Simple Moving Average) နှင့် EMA (Exponential Moving Average) ကဲ့သို့သော အဆင့်မြင့် Technical Indicators များကို ဖွင့်ပိတ်နိုင်ပါသည်။",
    
    feat2Title: "Interactive Predictor Terminal with Custom Leverage",
    feat2Desc: "ကိုယ့်ရဲ့ အလေ့အကျင့် လိုက်နာနိုင်စွမ်းပေါ်မှာ ယုံကြည်မှုရှိလား? Predictor Terminal တွင် ၁ ရက်၊ ၃ ရက် သို့မဟုတ် ၇ ရက်အပြီး consistency growth ခန့်မှန်းချက်များကို points များဖြင့် လောင်းကြေးထပ်ပါ။ Leverage (အကြွေးမြှောက်ဖော်ကိန်း) ကို တိုးမြှင့်အသုံးပြုပြီး ရရှိမည့် အပို bonus points ဆုများကို အဆပေါင်းများစွာ တိုးမြင့်ရယူနိုင်သည်။ Target မပြည့်ပါက Liquidate ဖြစ်ပြီး points ဆုံးရှုံးပါမည်။",
    feat2Low: "LOW RISK",
    feat2LowTitle: "1-Day Quick Scalp",
    feat2LowDesc: "1% Target / +15% Base Bonus / Leverage အနိမ့်ဆုံး",
    feat2Med: "MEDIUM RISK",
    feat2MedTitle: "3-Day Swing Trade",
    feat2MedDesc: "4% Target / +45% Base Bonus / အကောင်းဆုံးမျှတမှုရှိသောစနစ်",
    feat2High: "HIGH RISK",
    feat2HighTitle: "7-Day Ultimate Run",
    feat2HighDesc: "10% Target / +150% Base Bonus / ခြေရာခံမှုအပြည့်အဝဖြင့် တာဝန်ခံမှုအမြင့်ဆုံး",
    feat2Tip: "Liquidate ဖြစ်သွားသော points များအား Account Ledger (ငွေစာရင်း) ထဲတွင် ချက်ချင်းမှတ်တမ်းတင် နုတ်ယူသွားပါမည်။",
    
    feat3Title: "PUBG-Style Rank Tiers & Miss Penalties",
    feat3Desc: "သင့်ရဲ့စုစုပေါင်းရမှတ်များသည် သင့်၏ Account Rank အဆင့်ကို ဆုံးဖြတ်သည်။ Rank Level မြင့်မားလာပါက Predictor တွင် Max Bet ပိုတင်နိုင်ပြီး Leverage ပိုသုံးနိုင်မည်ဖြစ်သော်လည်း၊ တာဝန်ယူမှုပိုမိုရှိလာစေရန် အလေ့အကျင့်ပျက်ကွက်မှုအတွက် Miss Penalty factor ပိုများလာမည်ဖြစ်သည်။",
    feat3ColRank: "Rank & Status",
    feat3ColLimits: "Max Bet / Leverage",
    feat3ColPenalty: "Penalty Multiplier",
    feat3ColRange: "ရမှတ်အပိုင်းအခြား",
    feat3Bronze: "🥉 Bronze Tier (ကြေးဝါ)",
    feat3Silver: "🥈 Silver Tier (ငွေ)",
    feat3Gold: "🥇 Gold Tier (ရွှေ)",
    feat3Plat: "💎 Platinum Tier (ပလက်တီနမ်)",
    feat3Diamond: "💠 Diamond Tier (စိန်)",
    feat3Crown: "👑 Crown Tier (သရဖူ)",
    feat3Conq: "🌟 Conqueror Tier (အနိုင်ရသူ)",
    feat3Tip: "အဆင့်တစ်ခု၏ အမြင့်ဆုံးရမှတ်သို့ ရောက်ရှိပါက၊ နောက်တစ်ဆင့်သို့တက်လှမ်းရန် ၃ ရက်ကြာ ၇၅% consistency ကျော်လွန်ရမည့် Rank Promotion Match ကို ဖြတ်ကျော်ရပါမည်။ ရမှတ်များ ခဏ lock ဖြစ်နေပါမည်။",
    
    feat4Title: "Localized Schedule Controls for Real Lifestyles",
    feat4Desc: "လူတိုင်းသည် အချိန်ဇယားတစ်ခုတည်းနှင့် အသက်ရှင်သည်မဟုတ်ပါ။ သင့်နေ့စဉ်လူနေမှုဘဝနှင့် လိုက်လျောညီထွေဖြစ်စေရန် timing control စနစ်များကို ထည့်သွင်းပေးထားပါသည်။",
    feat4OwlTitle: "Night Owl Grace Hour Offset",
    feat4OwlDesc: "မနက်မိုးလင်းခါနီးအထိ ယမန်နေ့အတွက် tick ပေးနိုင်ရန် နေ့အကူးအပြောင်းအချိန်ကို 12 AM မှ 4 AM အထိ ရွှေ့ဆိုင်းသတ်မှတ်နိုင်သည်။ Streak မပြတ်စေရန် ကာကွယ်ပေးသည်။",
    feat4WeekendTitle: "Weekend Protection Mode",
    feat4WeekendDesc: "စနေ၊ တနင်္ဂနွေရက်များတွင် အပန်းဖြေအနားယူနိုင်ရန် Miss Penalty ဒဏ်ကြေး သက်ရောက်မှုမရှိအောင် ပိတ်ထားနိုင်သည်။",
    feat4SelectiveTitle: "Selective Custom Days",
    feat4SelectiveDesc: "အလေ့အကျင့်တစ်ခုချင်းစီကို သတ်မှတ်ထားသောနေ့များတွင်သာ စစ်ဆေးရန် ရွေးချယ်နိုင်သည်။ (ဥပမာ - Gym အား Mon/Wed/Fri သာဆော့ရန်)။ ကျန်ရက်များတွင် rest day အဖြစ် အလိုအလျောက် သတ်မှတ်ပေးသည်။",
    
    progTitle: "Progression Ladder & Rewards",
    progSub: "သင့်ရဲ့ လက်ရှိ Rank နှင့် ရှေ့ဆက်တက်လှမ်းရမည့် အဆင့်များကို နှိုင်းယှဉ်လေ့လာပါ။",
    yourRank: "သင့်လက်ရှိ Rank",
    
    guideTitle: "၁-၂-၃-၄ လွယ်ကူသော စတင်မှုလမ်းညွှန်",
    guideSub: "Habit Terminal အား ကျွမ်းကျင်စွာ အသုံးပြုနိုင်ရန် အခြေခံလမ်းညွှန်ချက်များ။",
    step1Title: "၁။ Asset သတ်မှတ်ရန်",
    step1Desc: "Assets Tab သို့သွားပြီး ခြေရာခံလိုသော Habits များကို ထည့်သွင်းပါ။ Risk Levels နှင့် Active Days များကို လွတ်လပ်စွာ သတ်မှတ်ပါ။",
    step2Title: "၂။ နေ့စဉ် လုပ်ဆောင်ရန်",
    step2Desc: "သတ်မှတ်ထားသောအလေ့အကျင့်များကို လုပ်ဆောင်ပြီး Overview Tab ရှိ live checklist တွင် ပြီးမြောက်ကြောင်း mark ပေးပါ။",
    step3Title: "၃။ ဇယားများ စောင့်ကြည့်ရန်",
    step3Desc: "Candlestick Chart တွင် သင့်တိုးတက်မှု အပိတ်ဈေးအတက်အကျ၊ SMA/EMA indicators များနှင့် trends များကို လေ့လာပါ။",
    step4Title: "၄။ Predict Option စမ်းသပ်ရန်",
    step4Desc: "ရရှိလာသော Points များကို အသုံးပြု၍ Predictor တွင် စိန်ခေါ်မှုများရယူပြီး bonus points များ အဆမတန် စုဆောင်းပါ။",
    
    footerTxt: "Bet On Me Terminal • Professional Consistency System v1.5.0 • Crafted for high-performance builders.",
    readyTitle: "စနစ် အဆင်သင့်ဖြစ်ပါပြီ",
    readyDesc: "ကိုယ့်ကိုယ်ကိုယ် တာဝန်ယူမှုအပြည့်ဖြင့် ရင်းနှီးမြှုပ်နှံလိုက်ပါ။ ယနေ့မှစတင်၍ သင်၏ Habits များကို စတင်ပြီးမြောက်အောင် လုပ်ဆောင်ပါ။"
  }
};

export const APP_LOCALIZATION = {
  en: {
    overview: "Overview",
    assets: "Assets",
    rankAndPrediction: "Rank & Prediction",
    audits: "Audits",
    ledger: "Ledger",
    settings: "Settings",
    habitIndexTerminal: "HABIT INDEX TERMINAL",
    streak: "D STREAK",
    syncEnabled: "Sync ✅",
    guestMode: "GUEST MODE",
    signOut: "Exit",
    restoreDefaultMockHistory: "Restore default mock history",
    
    // Settings translations:
    terminalConfigurations: "Terminal Configurations",
    setupYourPreferences: "Configure your terminal's operating schedules and core parameters.",
    nightOwlTitle: "Night Owl Boundary Offset",
    nightOwlDesc: "Delay the day rollover hour past midnight (e.g. 2:00 AM) to prevent breaking your streak if you complete habits late.",
    weekendProtectionTitle: "Weekend Protection Mode",
    weekendProtectionDesc: "Disable habit completion audits on Saturdays and Sundays. Miss penalties will not be charged on weekends.",
    customDaysTitle: "Selective Days Check-in",
    customDaysDesc: "Configure habits to run only on designated days of the week. Rest days are automatically handled.",
    dangerZone: "Danger Zone Operations",
    resetData: "Full Factory Reset",
    resetDataDesc: "Wipe all local and remote habit performance database tables and start from zero.",
    resetDataBtn: "Execute Reset",
    saveSettingsBtn: "Save Configurations",
    activeRank: "Active Operator Rank",
    maxLeverage: "Max Allowed Leverage",
    maxBet: "Max Points Bet Limit",
    dailyMissPenalty: "Daily Miss Penalty",
    pointsBracket: "Points Bracket",
    loading: "Decrypting data...",

    // Tab view notices
    rankUpAvailable: "Rank Up Available!",
    promoNotice: "Your performance score has surpassed {targetPoints} PTS! You can now deploy the 3-day high-performance promo challenge to advance to {targetTier}. Point growth is capped until activation.",
    startPromoBtn: "Initiate Promotion Protocol",
    activePromoChallenge: "Active Promotion Challenge",
    promoActiveNotice: "Main console locked in promotion mode. Maintain 75% consistency for {remainingDays} more days to achieve {targetTier}. Current streak: {streak} days.",
    promotedSuccess: "Promotion successful!",
    promotedMsg: "Congratulations operator! You have successfully been promoted to {tier}!",
    failedChallenge: "Challenge failed!",
    failedMsg: "You fell below the consistency target. The promotion contract was liquidated."
  },
  my: {
    overview: "ပင်မစာမျက်နှာ (Overview)",
    assets: "အလေ့အကျင့်များ (Assets)",
    rankAndPrediction: "အဆင့်နှင့်ခန့်မှန်းချက်များ",
    audits: "အစီရင်ခံစာ (Audits)",
    ledger: "ငွေစာရင်းစာအုပ် (Ledger)",
    settings: "ဆက်တင်များ (Settings)",
    habitIndexTerminal: "HABIT INDEX TERMINAL",
    streak: "ရက်ဆက်တိုက်",
    syncEnabled: "သိမ်းဆည်းပြီး ✅",
    guestMode: "ဧည့်သည်စနစ်",
    signOut: "ထွက်မည်",
    restoreDefaultMockHistory: "စမ်းသပ်မှတ်တမ်းဟောင်းများကို ပြန်ယူမည်",
    
    // Settings translations:
    terminalConfigurations: "စနစ် ဆက်တင်များ",
    setupYourPreferences: "Terminal ၏ လုပ်ဆောင်ပုံနှင့် အချိန်ဇယား ဆက်တင်များကို ချိန်ညှိပါ။",
    nightOwlTitle: "Night Owl နေ့အကူးအပြောင်းအချိန် ရွှေ့ဆိုင်းမှု",
    nightOwlDesc: "ညဥ့်နက်မှ အလေ့အကျင့်များ လုပ်ဆောင်လေ့ရှိသူများအတွက် နေ့အကူးအပြောင်းအချိန်ကို 12 AM မှ 4 AM အပြီးအထိ ရွှေ့ဆိုင်းသတ်မှတ်ပါ။",
    weekendProtectionTitle: "စနေ၊ တနင်္ဂနွေ ရက်ပိတ် စနစ်",
    weekendProtectionDesc: "စနေ၊ တနင်္ဂနွေရက်များတွင် အပန်းဖြေအနားယူနိုင်ရန် Miss Penalty ဒဏ်ကြေး သက်ရောက်မှုမရှိအောင် ပိတ်ထားပါ။",
    customDaysTitle: "သီးသန့်နေ့ရက်များတွင်သာ စစ်ဆေးခြင်း",
    customDaysDesc: "အလေ့အကျင့်တစ်ခုချင်းစီကို သတ်မှတ်ထားသောနေ့များတွင်သာ စစ်ဆေးရန် ရွေးချယ်နိုင်သည်။ ကျန်ရက်များတွင် rest day အဖြစ် သတ်မှတ်သည်။",
    dangerZone: "အရေးကြီး လုပ်ဆောင်ချက်များ",
    resetData: "စနစ်တစ်ခုလုံးကို Factory Reset ပြုလုပ်ရန်",
    resetDataDesc: "သင်၏ အလေ့အကျင့်များ၊ မှတ်တမ်းများနှင့် points အားလုံးကို ဖျက်ဆီးပြီး စနစ်အား အစမှ ပြန်လည်စတင်ပါ။",
    resetDataBtn: "Reset ပြုလုပ်မည်",
    saveSettingsBtn: "ဆက်တင်များ သိမ်းဆည်းမည်",
    activeRank: "လက်ရှိ Operator Rank",
    maxLeverage: "အများဆုံးအသုံးပြုနိုင်သော Leverage",
    maxBet: "အများဆုံး Points Bet တင်နိုင်မှု",
    dailyMissPenalty: "ပျက်ကွက်မှု ဒဏ်ကြေး",
    pointsBracket: "ရမှတ်အပိုင်းအခြား",
    loading: "ဒေတာများကို ယူဆောင်နေပါသည်...",

    // Tab view notices
    rankUpAvailable: "ရာထူးတိုးမြှင့်ရန် ရရှိနိုင်ပါပြီ!",
    promoNotice: "သင့်ရမှတ်သည် {targetPoints} PTS ပြည့်မီသွားပြီဖြစ်သဖြင့် {targetTier} သို့ ရာထူးတိုးမြှင့်ရန် စံတော်ချိန် ၃ ရက်စိန်ခေါ်မှုကို စတင်နိုင်ပါပြီ။ စတင်ခြင်းမပြုမီအထိ သင့်ရမှတ်များအား ယာယီပိတ်ထားပါမည်။",
    startPromoBtn: "ရာထူးတိုးမြှင့်မှု စိန်ခေါ်မှုစတင်မည်",
    activePromoChallenge: "လက်ရှိ ရာထူးတိုးမြှင့်မှု စိန်ခေါ်မှု",
    promoActiveNotice: "စနစ်ကို ရာထူးတိုးစိန်ခေါ်မှုစနစ်သို့ သတ်မှတ်ထားသည်။ {targetTier} အဆင့်သို့ တက်လှမ်းရန် နောက်ထပ် {remainingDays} ရက်အထိ အလေ့အကျင့် ၇၅% ကျော် ပြီးမြောက်အောင် ထိန်းသိမ်းပါ။ လက်ရှိရက်ဆက်: {streak} ရက်။",
    promotedSuccess: "ရာထူးတိုးမြှင့်ခြင်း အောင်မြင်ပါသည်!",
    promotedMsg: "ဂုဏ်ယူပါသည် Operator! သင်သည် {tier} အဆင့်သို့ အောင်မြင်စွာ တိုးမြှင့်ခြင်း ခံရပါပြီ!",
    failedChallenge: "စိန်ခေါ်မှု ကျရှုံးပါသည်!",
    failedMsg: "သတ်မှတ်ထားသော အလေ့အကျင့်စံနှုန်းအောက် လျော့နည်းသွားသဖြင့် ရာထူးတိုးမြှင့်မှု စာချုပ် ပျက်ပြယ်သွားပါပြီ။"
  }
};
